// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/BackTop/index.vue')['default']
    BlogFooter: typeof import('./src/components/Layout/footer/blog-footer.vue')['default']
    BlogHeader: typeof import('./src/components/Layout/header/blog-header.vue')['default']
    BlogMain: typeof import('./src/components/Layout/main/blog-main.vue')['default']
    BlogSearch: typeof import('./src/components/Search/blog-search.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Endpoint: typeof import('./src/components/endpoint/endpoint.vue')['default']
    First: typeof import('./src/components/WelcomeComps/first.vue')['default']
    Get: typeof import('./src/components/kv/get.vue')['default']
    GsapCount: typeof import('./src/components/GsapCount/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    MessageBox: typeof import('./src/components/MessageBox/message-box.vue')['default']
    MobileTopSkeleton: typeof import('./src/components/RightSide/components/skeleton/mobile-top-skeleton.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    RightSide: typeof import('./src/components/RightSide/right-side.vue')['default']
    RightSideItem: typeof import('./src/components/RightSide/components/item/right-side-item.vue')['default']
    RightSideSkeletonItem: typeof import('./src/components/RightSide/components/skeleton/right-side-skeleton-item.vue')['default']
    RightSideTop: typeof import('./src/components/RightSide/components/item/right-side-top.vue')['default']
    RightSideTopSkeleton: typeof import('./src/components/RightSide/components/skeleton/right-side-top-skeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Second: typeof import('./src/components/WelcomeComps/second.vue')['default']
    Set: typeof import('./src/components/kv/set.vue')['default']
    SkeletonItem: typeof import('./src/components/SkeletonItem/skeleton-item.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    SwitchTheme: typeof import('./src/components/SwitchTheme/index.vue')['default']
    Tooltip: typeof import('./src/components/ToolTip/tooltip.vue')['default']
    TypeWriter: typeof import('./src/components/TypeWriter/type-writer.vue')['default']
    Upload: typeof import('./src/components/Upload/upload.vue')['default']
  }
}
